name: CI - Preproduction

on:
  push:
    branches:
      - preprod

jobs:
  preproduction:
    name: Build preprod (preview)
    runs-on: ubuntu-latest

    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
